export const mockAthlete = {
  city: "London",
  firstname: "Jack",
  state: "Greater London",
  created_at: "2015-09-03T15:22:43Z",
  weight: 70,
  lastname: "Smith",
  profile_medium: ",",
  username: "nananananana",
  profile: "",
  updated_at: "2023-05-22T03:22:22Z",
  premium: true,
  bio: "Runner",
  badge_type_id: 1,
  resource_state: 2,
  friend: null,
  id: 9999999999,
  country: null,
  sex: "M",
  follower: null,
  summit: true,
};

export const mockActivities = [
  {
    resource_state: 2,
    athlete: {
      id: 9999999999,
      resource_state: 1,
    },
    name: "Run",
    distance: 15000,
    moving_time: 6000,
    elapsed_time: 6000,
    total_elevation_gain: 92.4,
    type: "Run",
    sport_type: "Run",
    workout_type: 0,
    id: 990909090,
    start_date: "2023-05-20T03:50:57Z",
    start_date_local: "2023-05-20T13:50:57Z",
    timezone: "(GMT+10:00) Australia/Melbourne",
    utc_offset: 36000,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 40,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {},
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: "g13089114",
    start_latlng: [],
    end_latlng: [],
    average_speed: 3.017,
    max_speed: 4.644,
    has_heartrate: true,
    average_heartrate: 149.9,
    max_heartrate: 169,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 54,
    elev_low: 26.4,
    upload_id: 9975151382,
    upload_id_str: "",
    external_id: "",
    from_accepted_tag: false,
    pr_count: 18,
    total_photo_count: 0,
    has_kudoed: false,
    suffer_score: 100,
  },
];
